# Site settings
title: "The Anengu Coffee Project: Solar Powered Coffee"
email: "sam@mead.fm"
description: > # this means to ignore newlines until "baseurl:"
  The Anengu Coffee Project is a sustainable initiative in a remote Papuan village.
baseurl: ""
url: "http://anengucoffeeproject.org"
github_username:  samjamead

# Build settings
markdown: kramdown
permalinks: pretty
